export const UPDATE_PLAYBACK = 'UPDATE_PLAYBACK';
export const STOP_PLAYBACK = 'STOP_PLAYBACK';

export const USER_PAUSE_MEDIA = 'USER_PAUSE_MEDIA';
export const USER_CLOSE = 'USER_CLOSE';

export const USER_NEXT_AUDIO = 'USER_NEXT_AUDIO';
export const USER_SEEK_FORWARD = 'USER_SEEK_FORWARD';
export const USER_TOGGLE_SUBTITLES = 'USER_TOGGLE_SUBTITLES';
export const USER_TOGGLE_VIDEO = 'USER_TOGGLE_VIDEO';
export const USER_SCREENSHOT = 'USER_SCREENSHOT';
export const USER_SCREEN_OFF = 'USER_SCREEN_OFF';
export const USER_OPEN_BROWSER = 'USER_OPEN_BROWSER';

export const PLAYING = 'PLAYING';
export const PAUSED = 'PAUSED';
export const STOPPED = 'STOPPED';
